version: '2'
services:
    web:
        build: .

        # ports:
        #     - '8000:8000'
        
        network_mode: 'host'
        depends_on:
            - db
    db:
        image: postgres:latest
        environment:
            - POSTGRES_DB=blockpy
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=toor
        network_mode: 'host'
