---
- name: clone and install dependencies for BlockPy
  hosts: peers
  remote_user: event1
  become_user: event1
  become: yes
  tasks:
  - name: Clone github repo
    git:
      repo: https://github.com/edrichhans/blockpy.git
      dest: /home/event1/blockpy
      clone: yes
      update: yes
      force: yes
    become_user: event1
    become: yes
  # - name: Shutdown docker containers
  #   shell: 'docker-compose -f ~/blockpy/docker-compose.yml down'

  # - name: Build docker images
  #   shell: 'docker-compose -f ~/blockpy/docker-compose.yml build'
 
  # - name: Run docker images
  #   shell: 'docker-compose -f ~/blockpy/docker-compose.yml up'
  

  

  
  
