---
- name: clone and install dependencies for BlockPy
  hosts: peers
  remote_user: event1
  become_user: event1
  become: yes

  vars:
    ansible_password: criticallysound
    ansible_become: yes
    ansible_become_method: enable

  tasks:
  # - name: Fix working tree permissions
  #   file: path=/home/tools owner=abc group=abc mode=0775 state=directory recurse=yes
  #Clone BlockPy
  - name: Clone github repo
    git:
      repo: https://github.com/edrichhans/blockpy.git
      dest: /home/event1/blockpy
      clone: yes
      update: yes
      force: yes
    become_user: event1
    become: yes

  - name: Build docker images
    become: yes
    become_method: enable
    shell: docker-compose -f ~/blockpy/docker-compose.yml build

  - name: Shutdown docker containers
    become: yes
    become_method: enable
    shell: docker-compose -f ~/blockpy/docker-compose.yml down
  
  - name: Run docker images
    become: yes
    become_method: enable
    shell: docker-compose -f ~/blockpy/docker-compose.yml up
  

  

  
  