---
- name: Fire messages!
  hosts: peers
  remote_user: event1
  become_user: event1
  become: yes

  tasks:
  - name: Test curl
    become: yes
    become_method: enable
    shell: bash /home/event1/blockpy/performance_test/curl-0.5.sh